[server]
runOnSave = false
fileWatcherType = "none"
maxUploadSize = 1000
maxMessageSize = 1000
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
